# Package information
LIBRARY = Selection
OBJDIR  = $(OBJ)
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include

# Include the generic compilation rules
include $(ANALYZER_DIR)/Makefile.common

INCLUDES += -I$(ANALYZER_DIR)/${Flag}Core/SKTree/include/
INCLUDES += -I$(ANALYZER_DIR)/${Flag}Core/AnalysisCore/include/
INCLUDES += -I$(ANALYZER_DIR)/${Flag}Core/Ntuplecore/include/
