# Package information
LIBRARY = AnalysisCore
OBJDIR  = $(OBJ)
DEPDIR  = $(OBJDIR)/dep
SRCDIR  = src
INCDIR  = include


# Include the generic compilation rules
include $(ANALYZER_DIR)/Makefile.common

INCLUDES += -I$(ANALYZER_DIR)/${Flag}Core/SKTree/include/
#INCLUDES += -I$(ANALYZER_DIR)/SNUTree/include/


